import { expect, test, type Page } from '@playwright/test'
import { writeFile } from 'node:fs/promises'

async function navigate(page: Page, name: string) {
  await page.locator('#workspace-navigation').waitFor({ state: 'attached' })
  const target = page.getByRole('navigation', { name: 'Workspace pages' }).getByRole('button', { name, exact: true })
  if (!await target.isVisible()) await page.getByRole('button', { name: 'Menu', exact: true }).click()
  await target.click()
}

for (const width of [1440, 1024, 390]) {
  test(`Northstar canonical journey and localized conflict at ${width}px`, async ({ page }, testInfo) => {
    test.setTimeout(90_000)
    await page.setViewportSize({ width, height: 1000 })
    let aiCalls = 0
    const errors: string[] = []
    const timings: Record<string, number> = {}
    page.on('pageerror', error => errors.push(error.message))
    await page.route('**/api/ai/**', route => { aiCalls++; return route.abort() })
    const capture = async (name: string) => {
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth && document.querySelector('main')!.scrollWidth <= document.querySelector('main')!.clientWidth + 1)).toBe(true)
      await page.screenshot({ path: testInfo.outputPath(`${name}-${width}.png`), animations: 'disabled' })
    }
    await page.goto('/')
    const loadedAt = Date.now()
    page.once('dialog', dialog => dialog.accept())
    await page.getByRole('button', { name: 'Load synthetic demo workspace', exact: true }).click()
    await expect(page.getByRole('region', { name: 'Primary investigation' })).toContainText('Northstar Commerce 3.2')
    await expect(page.getByRole('region', { name: 'Primary investigation' })).toContainText('Calculated: At Risk')
    timings.load = Date.now() - loadedAt
    await capture('dashboard')
    const inventory = await page.evaluate(async () => {
      const path = '/src/lib/workspace/workspaceRepository.ts'
      const { openWorkspaceRepository } = await import(/* @vite-ignore */ path)
      const repository = await openWorkspaceRepository()
      const sources = (await repository.readCollection('sources')).records.map((record: { value: { title: string; content: string } }) => record.value)
      const requirements = (await repository.readCollection('requirements')).records.map((record: { value: { summary: string } }) => record.value.summary)
      repository.close()
      return { sources: sources.map((source: { title: string; content: string }) => ({ title: source.title, length: source.content.length })), requirements }
    })
    expect(inventory.sources.map((source: { title: string }) => source.title)).toEqual(['Northstar Commerce Platform v3.2', 'Northstar Commerce Platform v3.3 Change Notice'])
    expect(inventory.sources[0].length).toBeGreaterThan(75000)
    expect(inventory.requirements).toHaveLength(119)
    expect(inventory.requirements.filter((summary: string) => !summary.startsWith('NCP-CHG-'))).toHaveLength(114)
    await page.getByRole('button', { name: 'Inspect the evidence', exact: true }).click()
    const source = page.getByRole('article', { name: 'Northstar Commerce Platform v3.2', exact: true })
    await expect(source).toBeVisible()
    await capture('sources')
    const browseAt = Date.now()
    await page.getByLabel('Find evidence', { exact: true }).fill('NCP-CHK-005')
    await expect(page.locator('.requirement-row')).toHaveCount(1)
    await page.getByRole('button', { name: /Open requirement: NCP-CHK-005/ }).click()
    const dossier = page.locator('.requirement-dossier')
    await expect(dossier.locator('blockquote')).toHaveText('Duplicate confirmation clicks must create at most one order.')
    await expect(dossier).toContainText('4 confirmed tests')
    timings.requirementSearch = Date.now() - browseAt
    await dossier.scrollIntoViewIfNeeded()
    await capture('evidence')
    await source.getByText('Source Structure', { exact: true }).click()
    await source.getByRole('radio').first().check()
    await source.getByRole('radio').first().scrollIntoViewIfNeeded()
    await capture('structure')
    await navigate(page, 'AI Coverage Workspace')
    const coverageAt = Date.now()
    const coverage = page.getByRole('region', { name: 'Requirement-backed global coverage' })
    await expect(coverage).toContainText('13 / 106')
    await page.getByRole('combobox', { name: 'Coverage attention', exact: true }).selectOption('failures')
    await expect(coverage.locator('summary').filter({ hasText: 'Checkout integrity' })).toBeVisible()
    await coverage.evaluate(element => element.scrollIntoView({ block: 'start' }))
    await capture('coverage')
    await coverage.locator('summary').filter({ hasText: 'Checkout integrity' }).click()
    await expect(coverage).toContainText('NCP-CHK-005')
    await expect(coverage).toContainText('1 findings with failures')
    timings.coverage = Date.now() - coverageAt
    await coverage.locator('.coverage-evidence-row').filter({ hasText: 'NCP-CHK-005' }).scrollIntoViewIfNeeded()
    await capture('coverage-detail')
    await navigate(page, 'Test Cases')
    await page.getByLabel('Search by title', { exact: true }).fill('NCP-CHK-005')
    await expect(page.locator('.test-library__row')).toHaveCount(4)
    await page.getByRole('article', { name: 'NCP-CHK-005 · Rapid double confirmation does not create a duplicate', exact: true }).getByRole('button', { name: 'Expand', exact: true }).click()
    await capture('tests')
    await navigate(page, 'Executions')
    await page.getByRole('button', { name: 'Show failed tests', exact: true }).click()
    await expect(page.locator('.execution-queue-item')).toHaveCount(1)
    await page.locator('.execution-queue-item').click()
    await expect(page.getByLabel('Execution notes', { exact: true })).toHaveValue(/BUG-DEMO-001/)
    await page.getByLabel('Execution notes', { exact: true }).scrollIntoViewIfNeeded()
    await capture('execution')
    await navigate(page, 'Bugs')
    await expect(page.getByRole('main')).toContainText('BUG-DEMO-001')
    await capture('bug')
    await navigate(page, 'Risks')
    await expect(page.getByRole('main')).toContainText('Marketplace return fallback')
    await capture('risk')
    await navigate(page, 'Release Report')
    await expect(page.getByRole('region', { name: 'Calculated Readiness' })).toContainText('At Risk')
    await expect(page.getByRole('region', { name: 'Calculated Readiness' })).toContainText('1 failed test case')
    await expect(page.getByRole('region', { name: 'Release requirement traceability', exact: true })).toContainText('13 / 110')
    await page.locator('.report-masthead').evaluate(element => element.scrollIntoView({ block: 'start' }))
    await capture('report')
    await navigate(page, 'AI Coverage Workspace')
    await page.getByRole('button', { name: 'Change impact', exact: true }).click()
    const impactAt = Date.now()
    const impact = page.getByRole('region', { name: 'Cross-source change impact' })
    const returns = impact.locator('details').filter({ hasText: 'Marketplace return fallback' })
    await returns.locator('summary').click()
    await expect(returns).toContainText('NCP-REF-003')
    await expect(returns).toContainText('NCP-CHG-001')
    await expect(returns).toContainText('NCP-REF-001 · Marketplace return eligibility requires policy review')
    await expect(returns).toContainText('Northstar Commerce 3.2')
    await expect(returns).toContainText('12 other requirements')
    await expect(returns).not.toContainText('NCP-CHK-005')
    timings.conflictImpact = Date.now() - impactAt
    await returns.scrollIntoViewIfNeeded()
    await capture('impact')
    await returns.getByRole('heading', { name: 'Linked Test Cases · review required' }).scrollIntoViewIfNeeded()
    await capture('impact-artifacts')
    await navigate(page, 'QA Sources')
    await page.getByRole('button', { name: 'Source sets', exact: true }).click()
    const set = page.getByRole('region', { name: 'Source set intelligence', exact: true })
    await expect(set).toContainText('Potential conflicts2')
    for (const summary of await set.locator('summary').filter({ hasText: 'Potential requirement conflict' }).all()) await summary.click()
    await expect(set).toContainText('no universal fallback window')
    await expect(set).toContainText('45-day return window')
    await set.scrollIntoViewIfNeeded()
    await capture('conflict')
    // The companion ambiguity must prevent a new QA confirmation, not merely display a warning.
    await navigate(page, 'Dashboard')
    await navigate(page, 'QA Sources')
    await page.getByLabel('Find evidence', { exact: true }).fill('NCP-REF-001')
    await page.getByRole('button', { name: /Open requirement: NCP-REF-001/ }).click()
    await page.locator('.requirement-dossier').getByRole('button', { name: 'Link reviewed tests', exact: true }).click()
    const approval = page.getByRole('dialog', { name: 'Link reviewed Test Cases' })
    await approval.getByLabel('Find Test Cases').fill('NCP-REF-001')
    await approval.getByRole('checkbox', { name: /NCP-REF-001/ }).check()
    await approval.getByRole('checkbox', { name: /I reviewed these 1 Test Cases/ }).check()
    await approval.getByRole('button', { name: 'Confirm reviewed coverage', exact: true }).click()
    await expect(approval.getByRole('alert')).toContainText('requires clarification')
    await capture('conflict-approval-guard')
    await approval.getByRole('button', { name: 'Cancel', exact: true }).click()
    expect(aiCalls).toBe(0)
    expect(errors).toEqual([])
    const performancePath = testInfo.outputPath('performance.json')
    await writeFile(performancePath, JSON.stringify({ width, timings, aiCalls, errors }, null, 2))
    await testInfo.attach('deterministic-performance', { path: performancePath, contentType: 'application/json' })
  })
}
