import { expect, test, type Page } from '@playwright/test'

async function navigate(page: Page, name: string) {
  const target = page.getByRole('navigation', { name: 'Workspace pages' }).getByRole('button', { name, exact: true })
  // After reload, wait for React to mount before deciding whether navigation is mobile.
  await page.locator('#workspace-navigation').waitFor({ state: 'attached' })
  if (!await target.isVisible()) await page.getByRole('button', { name: 'Menu', exact: true }).click()
  await target.click()
}

for (const width of [1440, 390, 1280, 1024]) {
  test(`portfolio journey at ${width}px: evidence, approval, failure and change impact without keys`, async ({ page }, testInfo) => {
    test.setTimeout(120_000)
    await page.setViewportSize({ width, height: 1000 })
    let calls = 0
    const errors: string[] = []
    page.on('pageerror', (error) => errors.push(error.message))
    await page.route('**/api/ai/**', async (route) => { calls++; await route.abort() })
    const capture = async (name: string) => {
      if (width === 390 && name !== 'first-run') await expect(page.locator('.workspace-local__short')).toBeVisible()
      expect(await page.evaluate(() => {
        const main = document.querySelector('main')!
        return document.documentElement.scrollWidth <= innerWidth && main.scrollWidth <= main.clientWidth + 1
      })).toBe(true)
      await page.screenshot({ path: testInfo.outputPath(`${name}-${width}.png`), animations: 'disabled' })
    }
    await page.goto('/')
    await expect(page.getByRole('region', { name: 'Explore the synthetic demo' })).toBeVisible()
    await capture('first-run')
    page.once('dialog', (dialog) => dialog.dismiss())
    await page.getByRole('button', { name: 'Load synthetic demo workspace' }).click()
    await expect(page.locator('.workspace-local')).toHaveText('Local workspace')
    page.once('dialog', (dialog) => dialog.accept())
    await page.getByRole('button', { name: 'Load synthetic demo workspace' }).click()
    await expect(page.getByRole('region', { name: 'Investigation route', exact: true })).toBeVisible({ timeout: 30_000 })
    await capture('dashboard')
    await page.getByRole('button', { name: 'Inspect the evidence', exact: true }).click()
    await expect(page.getByRole('main')).toBeFocused()
    const source = page.getByRole('article', { name: 'Northstar Commerce Platform v3.2', exact: true })
    await expect(source).toBeVisible()
    await capture('sources')
    await page.locator('.requirement-collection .requirement-row').filter({ hasText: 'NCP-CHK-005' }).click()
    const requirement = page.locator('.requirement-dossier')
    await expect(requirement.locator('blockquote')).toHaveText('Duplicate confirmation clicks must create at most one order.')
    await requirement.scrollIntoViewIfNeeded()
    await capture('evidence')
    await requirement.getByRole('button', { name: 'Link reviewed tests' }).click()
    const dialog = page.getByRole('dialog', { name: 'Link reviewed Test Cases' })
    await dialog.getByLabel('Find Test Cases').fill('Single confirmation')
    await dialog.getByRole('checkbox', { name: /Single confirmation creates one order/ }).check()
    await expect(dialog.getByRole('button', { name: 'Confirm reviewed coverage' })).toBeDisabled()
    await dialog.getByText('Review test design', { exact: true }).click()
    await capture('qa-confirmation')
    await dialog.getByRole('checkbox', { name: /I reviewed these 1 Test Cases/ }).check()
    await dialog.getByRole('button', { name: 'Confirm reviewed coverage' }).click()
    await expect(dialog).not.toBeVisible()
    await expect(page.getByRole('heading', { name: 'Global Coverage Plan', exact: true })).toBeVisible()
    await page.getByRole('heading', { name: 'Global Coverage Plan', exact: true }).scrollIntoViewIfNeeded()
    await capture('coverage')
    await page.getByRole('heading', { name: 'Global Coverage Plan', exact: true }).evaluate((element) => element.scrollIntoView({ block: 'start' }))
    await capture('coverage-detail')
    await navigate(page, 'Test Cases')
    const testCase = page.getByRole('article', { name: 'NCP-CHK-005 · Single confirmation creates one order', exact: true })
    await testCase.getByRole('button', { name: 'Expand', exact: true }).click()
    await testCase.scrollIntoViewIfNeeded()
    await capture('test-design')
    await navigate(page, 'Test Suites')
    await capture('suites')
    await navigate(page, 'Executions')
    await page.getByRole('button', { name: 'Show failed tests' }).click()
    await expect(page.locator('.execution-queue-item')).toHaveCount(1)
    await capture('execution')
    if (width === 390) {
      await page.locator('.execution-queue-item').first().click()
      await expect(page.locator('.execution-queue-panel')).not.toBeVisible()
      await expect(page.locator('.execution-runner-card h3')).toBeFocused()
    }
    await page.getByLabel('Execution notes', { exact: true }).scrollIntoViewIfNeeded()
    await expect(page.getByLabel('Execution notes', { exact: true })).toHaveValue(/two order IDs/)
    await capture('execution-observation')
    if (width === 390) {
      await page.getByRole('button', { name: 'Back to execution queue', exact: true }).click()
      await expect(page.locator('.execution-queue-item').first()).toBeFocused()
      await expect(page.locator('.execution-runner-panel')).not.toBeVisible()
    }
    await navigate(page, 'Bugs')
    await capture('bugs')
    await navigate(page, 'Release Report')
    await capture('report-overview')
    const report = page.getByRole('region', { name: 'Release requirement traceability', exact: true })
    await expect(report).toContainText('QA-confirmed tests13 / 110')
    await expect(report).toContainText('Linked recorded failures1')
    await expect(report).toContainText('9 ambiguities')
    await report.scrollIntoViewIfNeeded()
    await capture('release')
    await navigate(page, 'QA Sources')
    await page.getByRole('button', { name: 'Source sets', exact: true }).click()
    const set = page.getByRole('region', { name: 'Source set intelligence', exact: true })
    await expect(set.locator('summary').filter({ hasText: 'Potential requirement conflict' })).toHaveCount(2)
    for (const summary of await set.locator('summary').filter({ hasText: 'Potential requirement conflict' }).all()) await summary.click()
    await expect(set).toContainText('no universal fallback window')
    await expect(set).toContainText('45-day return window')
    await set.scrollIntoViewIfNeeded()
    await capture('conflict')
    await navigate(page, 'Dashboard')
    await navigate(page, 'QA Sources')
    await source.getByRole('button', { name: 'Edit', exact: true }).click()
    const editor = page.getByRole('dialog')
    // Native editor must contain keyboard navigation, dismiss with Escape,
    // restore its trigger, and preserve source text when canceled.
    const originalContent = await editor.getByLabel('Source content', { exact: true }).inputValue()
    await editor.getByRole('button', { name: 'Cancel', exact: true }).focus()
    await page.keyboard.press('Tab')
    // Chromium may stop on browser chrome (activeElement=body) at a native
    // dialog boundary; it must never focus the inert application behind it.
    expect(await page.evaluate(() => document.activeElement === document.body || Boolean(document.activeElement?.closest('dialog')))).toBe(true)
    await page.keyboard.press('Tab')
    await expect.poll(() => editor.evaluate((element) => element.contains(document.activeElement))).toBe(true)
    await page.keyboard.press('Escape')
    await expect(editor).not.toBeVisible()
    await expect(source.getByRole('button', { name: 'Edit', exact: true })).toBeFocused()
    await source.getByRole('button', { name: 'Edit', exact: true }).click()
    await expect(editor.getByLabel('Source content', { exact: true })).toHaveValue(originalContent)
    const content = editor.getByLabel('Source content', { exact: true })
    await content.fill((await content.inputValue()).replace('**Requirement:** Duplicate confirmation clicks must create at most one order.', '**Requirement:** Duplicate confirmation clicks must create exactly one order.'))
    await content.scrollIntoViewIfNeeded()
    const sourceBox = await content.boundingBox()
    const footerBox = await editor.locator('.modal-footer').boundingBox()
    expect(sourceBox && footerBox && sourceBox.y + sourceBox.height <= footerBox.y + 1).toBe(true)
    await capture('source-edit')
    await editor.getByRole('button', { name: 'Save changes', exact: true }).click()
    await page.getByRole('button', { name: 'Change impact', exact: true }).click()
    await expect(page.getByRole('region', { name: 'Requirement change impact' })).toContainText('Duplicate confirmation')
    const impact = page.getByRole('region', { name: 'Requirement change impact' })
    await impact.locator('.document-result').filter({ hasText: 'Duplicate confirmation' }).locator('summary').click()
    await expect(impact).toContainText('Test Cases')
    await impact.evaluate((element) => element.scrollIntoView({ block: 'start' }))
    await capture('change-impact')
    await page.reload()
    await navigate(page, 'Release Report')
    await expect(report).toContainText('Linked recorded failures')
    expect(calls).toBe(0)
    expect(errors).toEqual([])
  })
}
